source_files = \
	core/src/processing/core/PApplet.java \
	core/src/processing/core/PConstants.java \
	core/src/processing/core/PFont.java \
	core/src/processing/core/PGraphics.java \
	core/src/processing/core/PGraphicsJava2D.java \
	core/src/processing/core/PGraphicsRetina2D.java \
	core/src/processing/core/PImage.java \
	core/src/processing/core/PMatrix.java \
	core/src/processing/core/PMatrix2D.java \
	core/src/processing/core/PMatrix3D.java \
	core/src/processing/core/PShape.java \
	core/src/processing/core/PShapeOBJ.java \
	core/src/processing/core/PShapeSVG.java \
	core/src/processing/core/PStyle.java \
	core/src/processing/core/PVector.java \
	core/src/processing/data/FloatDict.java \
	core/src/processing/data/FloatList.java \
	core/src/processing/data/IntDict.java \
	core/src/processing/data/IntList.java \
	core/src/processing/data/JSONArray.java \
	core/src/processing/data/JSONObject.java \
	core/src/processing/data/JSONTokener.java \
	core/src/processing/data/Sort.java \
	core/src/processing/data/StringDict.java \
	core/src/processing/data/StringList.java \
	core/src/processing/data/Table.java \
	core/src/processing/data/TableRow.java \
	core/src/processing/data/XML.java \
	core/src/processing/event/Event.java \
	core/src/processing/event/KeyEvent.java \
	core/src/processing/event/MouseEvent.java \
	core/src/processing/event/TouchEvent.java \
	core/src/processing/opengl/FontTexture.java \
	core/src/processing/opengl/FrameBuffer.java \
	core/src/processing/opengl/LinePath.java \
	core/src/processing/opengl/LineStroker.java \
	core/src/processing/opengl/PGL.java \
	core/src/processing/opengl/PGraphics2D.java \
	core/src/processing/opengl/PGraphics3D.java \
	core/src/processing/opengl/PGraphicsOpenGL.java \
	core/src/processing/opengl/PJOGL.java \
	core/src/processing/opengl/PShader.java \
	core/src/processing/opengl/PShapeOpenGL.java \
	core/src/processing/opengl/Texture.java \
